### ISSUE TITLE
All coontact member pages go to 500 errors on http

### ISSUE THREAD

**Issue by gruunday** [redbrick/static-site#163]
http://www.redbrick.dcu.ie/about/committee/

All links go to 500 errors. Should be handled gracefully until smtp server is set up

**Comment by gruunday** [comment]
This issue is only on http

**Comment by butlerx** [comment]
this due to dynamic content being served only over https for security reasons 
https redirect should be enabled on www to stop this

**Comment by butlerx** [comment]
the site is now always in https so this should be closed
