### ISSUE TITLE
Rename repo to website

### ISSUE THREAD

**Issue by VoyTechnology** [redbrick/static-site#170]
I believe this was named static-site because it was moved from butlerx's own repo. Should we not remove the current `website` repo and rename this one?

**Comment by butlerx** [comment]
it was named static site because it originally didnt have the node server for api and emailing, so was a statically generated site
tbh i still like it also its name is quite a few places in prod now. 
i also dont think we should delete the old repo

**Comment by butlerx** [comment]
@VoyTechnology as of #314 the site will once more be a solely static-site
