### ISSUE TITLE
Add CodeClimate

### ISSUE THREAD

**Issue by VoyTechnology** [redbrick/static-site#186]
https://codeclimate.com allows free code heath analysis for open source. I think it would be worth adding it.

**Comment by butlerx** [comment]
ive enabled it https://codeclimate.com/github/redbrick/static-site but because we arnt a org we can itegrate it with pr

**Comment by butlerx** [comment]
as you can see from #187  ive added auto issue creation this is set up with my account for now if we like it we should move it to @redbrickCmt

**Comment by VoyTechnology** [comment]
I wasn't necessary thinking of filing issues. We need a `.codeclimate` file, with preferably https://docs.codeclimate.com/v1.0/docs/markdownlint. Adding the run for each PR would prevent stupid mistakes and allow us to have a uniform markdown guide. Maybe not necessary block submits, but as additional tool for reviewers.

Reopening for now. I will add the `.codeclimate.yml` file and then close this.
