### ISSUE TITLE
Recapcha error on /about/contact/treasurer

### ISSUE THREAD

**Issue by benmcmahon100** [redbrick/static-site#228]
![image](https://user-images.githubusercontent.com/10749142/31121523-75688c7e-a830-11e7-85c1-c7d3ca788d18.png)

**Comment by benmcmahon100** [comment]
As in recapcha key?

**Comment by butlerx** [comment]
yes

**Comment by benmcmahon100** [comment]
Just got the logs there. I'll sort it out now
