### ISSUE TITLE
2 Codes of conduct

### ISSUE THREAD

**Issue by butlerx** [redbrick/static-site#251]
FYI you've 3 codes of conduct

https://github.com/redbrick/static-site/blob/master/CODE_OF_CONDUCT.md
https://github.com/redbrick/static-site/blob/master/CONTRIBUTING.md#code-of-conduct

**Comment by CSmartt** [comment]
s/3/2/g ?

**Comment by CSmartt** [comment]
Assigning this to you, you put them both here.

**Comment by CSmartt** [comment]
߷

**Comment by butlerx** [comment]
yes 2 

its a bit of an everyone decision as they are both it to you 
also that emoji doesnt work

**Comment by CSmartt** [comment]
![fidget](https://user-images.githubusercontent.com/9290221/31863686-e175e408-b748-11e7-88ef-b562fd9bbf6f.png)

They are both what?

**Comment by butlerx** [comment]
sorry as they were both reviewed and merged and they are different

**Comment by CSmartt** [comment]
https://github.com/redbrick/static-site/pull/205
https://github.com/redbrick/static-site/commit/555e08e78510c42537c957d915725d8fffc31943#diff-6a3371457528722a734f3c51d9238c13

You put them both here, I'd rather a PR to delete one of them, or something more proactive than this issue.

**Comment by butlerx** [comment]
im not denneying i added them im just saying its not my decision which gets taken in to effect

**Comment by GoldenBadger** [comment]
Resolved by #252.
