### ISSUE TITLE
Missing issue template and pull request template.

### ISSUE THREAD

**Issue by GoldenBadger** [redbrick/static-site#253]
According to https://github.com/redbrick/static-site/community, we should have an [issue template](https://help.github.com/articles/creating-an-issue-template-for-your-repository/) and a [pull request template](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/), to make it easier for people to contribute.

**Comment by GoldenBadger** [comment]
I am currently working on this.

**Comment by CSmartt** [comment]
Closed by #256
