### ISSUE TITLE
Add Google Calendar Link to Site

### ISSUE THREAD

**Issue by cliodhnaharrison** [redbrick/static-site#311]
### Expected behaviour
Add google calendar link to websites so brickies can add the calendar to their own google calendar.

### Actual behaviour
No current link.

### Checklist

*I confirm that before I submitted this issue I did the following:*

- [X] Cleared my cookies.
- [X] Cleared my cache.
- [X] Refreshed the page.

**Comment by Frazl** [comment]
@cliodhnaharrison can you supply me with a google calendar link and I'll do this. :D

**Comment by cliodhnaharrison** [comment]
@Frazl This should be the right link, https://calendar.google.com/calendar/embed?src=r2l6edh5l8jm5t9dbfi84rn26s%40group.calendar.google.com&ctz=Europe%2FDublin

**Comment by theycallmemac** [comment]
@Frazl have you gotten around to this yet?

**Comment by cliodhnaharrison** [comment]
@butlerx yeah we know, this is a different issue. This is to add a link to the site so people can add the red brick calendar to their own google calendar

**Comment by butlerx** [comment]
then you want the subscribe link not the embed link https://calendar.google.com/calendar/r?cid=r2l6edh5l8jm5t9dbfi84rn26s@group.calendar.google.com
