### ISSUE TITLE
Missing Colons On Site Generation Failing Circleci

### ISSUE THREAD

**Issue by Frazl** [redbrick/static-site#312]
### Issue

circleci test is failing because of a script tag that gets automatically put into the html and minified.

`<script type="text/javascript">!function(e,a,t,n,c,o,s){e.GoogleAnalyticsObject=c,e[c]=e[c]||function(){(e[c].q=e[c].q||[]).push(arguments)},e[c].l=1*new Date,o=a.createElement(t),s=a.getElementsByTagName(t)[0],o.async=1,o.src="//www.google-analytics.com/analytics.js",s.parentNode.insertBefore(o,s)}(window,document,"script",0,"ga"),ga("create","UA-85359173-1","auto"),ga("send","pageview")</script>`

Should be

`<script type="text/javascript">!function(e,a,t,n,c,o,s){e.GoogleAnalyticsObject=c,e[c]=e[c]||function(){(e[c].q=e[c].q||[]).push(arguments)},e[c].l=1*new Date,o=a.createElement(t),s=a.getElementsByTagName(t)[0],o.async=1,o.src="//www.google-analytics.com/analytics.js",s.parentNode.insertBefore(o,s)}(window,document,"script",0,"ga"),ga("create","UA-85359173-1","auto"),ga("send","pageview");</script>`

It's just missing a `;` at the end of the function before the closing of the script tag.

Code still runs perfectly on local host and this missing colon is currently occurring on the master branch. This can be seen on the master branch by loading current site and looking at any html page source code and seeing the missing colon.

I presume this issue is due to an update with the HTMLproofer which gets pulled from a repo everytime the test is run. 

Alternatively this could be seen as an issue with the minifier as that's what is removing the colon when minifying. Anyone can easily debate whether or not that colon should be there but the code executes perfectly each time still. 

### Checklist

*I confirm that before I submitted this issue I did the following:*

- [x] Cleared my cookies.
- [x] Cleared my cache.
- [x] Refreshed the page.

**Comment by theycallmemac** [comment]
@butlerx any ideas on this?

**Comment by butlerx** [comment]
this is a check for `;` in alt tags thats failing when did the issue first appear

**Comment by m1cr0man** [comment]
It only seems to have started happening in [build 861](https://circleci.com/gh/redbrick/static-site/861). Tests post this which succeeded seemed to have skipped the "Test Internal Links" step.

We had a look into changing the minifier options and adding "semicolons: false" (to stop it removing them) to no avail. Also this is a dependency in the theme - totally disjoint from the changes triggering the build. Not sure how to resolve this other than not minifing.

**Comment by butlerx** [comment]
the issue seems to be coming from the use of `&` in a tag [here](https://github.com/redbrick/static-site/commit/0219342d909fb4bfacb28355a38a10de70714784#diff-a162b7d2393e6988ed776c65b098c639R7) These tags appear not to be normalized for HTML eg `&` -> `&amp;`
the reason for adding a `;` in the script tag is probably just a regex quirk

i suggested either using `C&amp;S` or `CandS`

**Comment by theycallmemac** [comment]
I'll fix it, have more announces and minutes to add between today & tomorrow

**Comment by theycallmemac** [comment]
Closed by #309
