### ISSUE TITLE
move contact page and api endpoint to routes

### ISSUE THREAD

**Issue by butlerx** [redbrick/static-site#36]
They are currently part of app.js it would make the code more maintainable if they where moved to their own files in `./routes`

**Comment by samanthakem** [comment]
I will work on this one :)

**Comment by blanxii** [comment]
Done in PR #37

**Comment by samanthakem** [comment]
:| I had the PR for this one already but I was figuring a good way to refactor the code... the code inside the app.get is too long for the routes.js :( anyways ..........
