### ISSUE TITLE
Email update word wrap applied too many times/redundant.

### ISSUE THREAD

**Issue by benwiley4000** [redbrick/static-site#41]
In `emailNewPosts.js` the `wrap80` function for applying an 80-character word wrap is applied to the email body for each individual email that is sent. If *n* is the number of posts and *m* is the number of email addresses, `wrap80` is applied *n* X *m* times. It is only necessary to wrap each message body once, so *n* times only.

For a sufficiently large email list this could become a problem, so it should be patched.

**Comment by VoyTechnology** [comment]
Resolved in #42
