### ISSUE TITLE
merge _config.yaml and config.json

### ISSUE THREAD

**Issue by butlerx** [redbrick/static-site#44]
_config.yaml is from the hexo generation and confg.json is used for express server but we should be able to use them just one with both variables in it 
because _config.yaml is needed for hexo itll have to be merged in to that

**Comment by BrianDGLS** [comment]
Picking this up.

**Comment by BrianDGLS** [comment]
@butlerx Let me know if this what you needed. Thanks.

https://github.com/redbrick/static-site/pull/46

**Comment by butlerx** [comment]
closed in #46
