### ISSUE TITLE
add error and error handling through express

### ISSUE THREAD

**Issue by butlerx** [redbrick/static-site#47]
currently we just server a static error page it would be good if we could serve a page with an actual error generated by express

**Comment by nunofaria11** [comment]
Hi again, I would like to help with this.

**Comment by butlerx** [comment]
cool lwt us know if you need anyting

**Comment by nunofaria11** [comment]
Hi, sorry for the delay - was wondering if something like [this ](https://github.com/nunofaria11/static-site/commit/92498ffee77892feaa56b12829ca6dd683ab9e33) is enough

**Comment by butlerx** [comment]
done in #65
