### ISSUE TITLE
add api end point to return exam and tutorial info 

### ISSUE THREAD

**Issue by butlerx** [redbrick/static-site#48]
api endpoint to return info about the exam pages and tutorial pages, 
- [ ] list of exam types
- [ ] list of exam years 
- [ ] links to exam contents
- [ ] list of all tutorials 
- [ ] links to tutorial content 

check `public/content.json` for this info or have it generated when the site is generated

**Comment by avipatel91** [comment]
Do you want the api end point to be written in app.js?

**Comment by butlerx** [comment]
definea route and add it to the app.js
