### ISSUE TITLE
Additional Labels

### ISSUE THREAD

**Issue by VoyTechnology** [redbrick/static-site#54]
Maybe we should create additional labels like we had in redbrick/website repo to indicate the difficulty of a particular tasks etc?

**Comment by butlerx** [comment]
they work as long as we done make too many labels beginner, intermediate, hard is all we need in labels and possibly an upfor grabs

**Comment by butlerx** [comment]
Ive made the labels as well as an `up for grabs` for things that don't seem appropriate for hacktoberfest but still open to the community to do
