### ISSUE TITLE
minimize html

### ISSUE THREAD

**Issue by butlerx** [redbrick/static-site#73]

**Comment by aliasm2k** [comment]
Hello, I would like to fix this issue... By the way, seems like you have a duplicate issue here #70

Going through your package.json, I didnt notice any plugins capable of minimizing html. So, wanted to discuss with you on how you intend have this fixed...

**Comment by butlerx** [comment]
Hey sorry id already started work on this

**Comment by butlerx** [comment]
so the reason there was a duplicate was i meant to make the issue [here](https://github.com/redbrick/techweek.dcu.ie/issues/54)
